# Dockerfile
FROM mysql:latest

# Variables de entorno para configurar la base de datos
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=root
ENV MYSQL_USER=java
ENV MYSQL_PASSWORD=pass

# Copia tu script SQL para inicializar la base de datos (si es necesario)
#COPY mysql -u root -p
